// client/src/App.svelte
<script>
  import { onMount } from 'svelte'
  import { isAuthenticated, username, activeTab } from './lib/stores.js'
  import LoginForm from './components/LoginForm.svelte'
  import CheckForm from './components/CheckForm.svelte'
  import EgaisForm from './components/EgaisForm.svelte'
  import ProductsView from './components/ProductsView.svelte'
  import KktInfo from './components/KktInfo.svelte'
  import UsersView from './components/UsersView.svelte'
  import LogsView from './components/LogsView.svelte'
  import StatsView from './components/StatsView.svelte'
  import Logo from './components/Logo.svelte'

  let currentUsername = ''
  let currentAuth = false
  let currentTab = 'checks'

  $: currentUsername = $username
  $: currentAuth = $isAuthenticated
  $: currentTab = $activeTab

  onMount(() => {
    const token = localStorage.getItem('token')
    const savedUsername = localStorage.getItem('username')
    
    if (token && savedUsername) {
      isAuthenticated.set(true)
      username.set(savedUsername)
    }
  })

  function handleLogout() {
    localStorage.removeItem('token')
    localStorage.removeItem('username')
    isAuthenticated.set(false)
    username.set('')
    activeTab.set('checks')
  }

  function handleMenuSelect(tab) {
    activeTab.set(tab)
  }
</script>

<div class="min-h-screen bg-gray-50">
  {#if !currentAuth}
    <LoginForm />
  {:else}
    <div class="flex flex-col h-screen">
      <!-- Header -->
      <header class="bg-primary-500 text-white shadow-md">
        <div class="flex items-center justify-between px-4 h-16">
          <div class="flex items-center gap-3">
            <Logo />
            <span class="text-lg font-semibold">Ресторан</span>
          </div>
          
          <nav class="flex-1 flex items-center justify-center gap-1 overflow-x-auto">
            <button
              class="px-4 py-2 rounded-md transition-colors {currentTab === 'checks' ? 'bg-primary-600' : 'hover:bg-primary-600'}"
              on:click={() => handleMenuSelect('checks')}
            >
              Чеки
            </button>
            <button
              class="px-4 py-2 rounded-md transition-colors {currentTab === 'egais' ? 'bg-primary-600' : 'hover:bg-primary-600'}"
              on:click={() => handleMenuSelect('egais')}
            >
              ЕГАИС
            </button>
            <button
              class="px-4 py-2 rounded-md transition-colors {currentTab === 'products' ? 'bg-primary-600' : 'hover:bg-primary-600'}"
              on:click={() => handleMenuSelect('products')}
            >
              Товары
            </button>
            <button
              class="px-4 py-2 rounded-md transition-colors {currentTab === 'kkt' ? 'bg-primary-600' : 'hover:bg-primary-600'}"
              on:click={() => handleMenuSelect('kkt')}
            >
              ККТ
            </button>
            <button
              class="px-4 py-2 rounded-md transition-colors {currentTab === 'users' ? 'bg-primary-600' : 'hover:bg-primary-600'}"
              on:click={() => handleMenuSelect('users')}
            >
              Пользователи
            </button>
            <button
              class="px-4 py-2 rounded-md transition-colors {currentTab === 'logs' ? 'bg-primary-600' : 'hover:bg-primary-600'}"
              on:click={() => handleMenuSelect('logs')}
            >
              Логи
            </button>
            <button
              class="px-4 py-2 rounded-md transition-colors {currentTab === 'stats' ? 'bg-primary-600' : 'hover:bg-primary-600'}"
              on:click={() => handleMenuSelect('stats')}
            >
              Статистика
            </button>
          </nav>
          
          <div class="flex items-center gap-3 ml-4">
            <span class="text-sm">{currentUsername}</span>
            <button
              class="px-3 py-1 text-sm bg-danger-500 hover:bg-danger-600 rounded-md transition-colors"
              on:click={handleLogout}
            >
              Выход
            </button>
          </div>
        </div>
      </header>
      
      <!-- Main Content -->
      <main class="flex-1 overflow-auto p-5">
        {#if currentTab === 'checks'}
          <CheckForm />
        {:else if currentTab === 'egais'}
          <EgaisForm />
        {:else if currentTab === 'products'}
          <ProductsView />
        {:else if currentTab === 'kkt'}
          <KktInfo />
        {:else if currentTab === 'users'}
          <UsersView />
        {:else if currentTab === 'logs'}
          <LogsView />
        {:else if currentTab === 'stats'}
          <StatsView />
        {/if}
      </main>
    </div>
  {/if}
</div>

// client/src/App.vue
<template>
  <div id="app">
    <!-- Форма авторизации -->
    <LoginForm v-if="!isAuthenticated" @login-success="handleLoginSuccess" />
    
    <!-- Основное приложение -->
    <el-container v-else>
      <el-header>
        <div class="header-left">
          <Logo />
          <span class="app-title">Ресторан</span>
        </div>
        <el-menu mode="horizontal" :default-active="activeTab" @select="handleMenuSelect" class="main-menu">
          <el-menu-item index="checks">
            <el-icon><Document /></el-icon>
            <span>Чеки</span>
          </el-menu-item>
          <el-menu-item index="egais">
            <el-icon><Box /></el-icon>
            <span>ЕГАИС</span>
          </el-menu-item>
          <el-menu-item index="products">
            <el-icon><ShoppingBag /></el-icon>
            <span>Товары</span>
          </el-menu-item>
          <el-menu-item index="kkt">
            <el-icon><Monitor /></el-icon>
            <span>ККТ</span>
          </el-menu-item>
          <el-menu-item index="users">
            <el-icon><User /></el-icon>
            <span>Пользователи</span>
          </el-menu-item>
          <el-menu-item index="logs">
            <el-icon><Document /></el-icon>
            <span>Логи</span>
          </el-menu-item>
          <el-menu-item index="stats">
            <el-icon><DataAnalysis /></el-icon>
            <span>Статистика</span>
          </el-menu-item>
        </el-menu>
        <div class="header-right">
          <span class="username">{{ username }}</span>
          <el-button size="small" @click="handleLogout" type="danger" plain>Выход</el-button>
        </div>
      </el-header>
      
      <el-main>
        <CheckForm v-if="activeTab === 'checks'" @check-created="handleCheckCreated" />
        <EgaisForm v-if="activeTab === 'egais'" @egais-sent="handleEgaisSent" />
        <ProductsView v-if="activeTab === 'products'" />
        <KktInfo v-if="activeTab === 'kkt'" />
        <UsersView v-if="activeTab === 'users'" />
        <LogsView v-if="activeTab === 'logs'" />
        <StatsView v-if="activeTab === 'stats'" />
      </el-main>
    </el-container>
  </div>
</template>

<script>
import CheckForm from './components/CheckForm.vue'
import EgaisForm from './components/EgaisForm.vue'
import EgaisXmlUploadForm from './components/EgaisXmlUploadForm.vue'
import ProductsView from './components/ProductsView.vue'
import KktInfo from './components/KktInfo.vue'
import UsersView from './components/UsersView.vue'
import LogsView from './components/LogsView.vue'
import StatsView from './components/StatsView.vue'
import LoginForm from './components/LoginForm.vue'
import Logo from './components/Logo.vue'
import { ElMessage } from 'element-plus'
import { Document, Box, ShoppingBag, Monitor, User, DataAnalysis } from '@element-plus/icons-vue'

export default {
  name: 'App',
  components: {
    CheckForm,
    EgaisForm,
    EgaisXmlUploadForm,
    ProductsView,
    KktInfo,
    UsersView,
    LogsView,
    StatsView,
    LoginForm,
    Logo,
    Document,
    Box,
    ShoppingBag,
    Monitor,
    User,
    DataAnalysis
  },
  data() {
    return {
      activeTab: 'checks',
      isAuthenticated: false,
      username: ''
    }
  },
  mounted() {
    // Проверяем, есть ли сохраненный токен
    const token = localStorage.getItem('token')
    const savedUsername = localStorage.getItem('username')
    
    if (token && savedUsername) {
      this.isAuthenticated = true
      this.username = savedUsername
    }
  },
  methods: {
    handleMenuSelect(key) {
      this.activeTab = key
    },
    handleCheckCreated(result) {
      this.$message.success('Чек создан: ' + result.message)
    },
    handleEgaisSent(result) {
      this.$message.success('ЕГАИС: ' + result.message)
    },
    handleLoginSuccess() {
      this.isAuthenticated = true
      this.username = localStorage.getItem('username')
      ElMessage.success('Добро пожаловать!')
    },
    handleLogout() {
      localStorage.removeItem('token')
      localStorage.removeItem('username')
      this.isAuthenticated = false
      this.username = ''
      this.activeTab = 'checks'
      ElMessage.success('Вы вышли из системы')
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.el-header {
  background-color: #409EFF;
  color: white;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 15px;
  height: 60px;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 12px;
  flex-shrink: 0;
}

.app-title {
  font-size: 18px;
  font-weight: 600;
  color: white;
}

.header-right {
  display: flex;
  align-items: center;
  gap: 12px;
  flex-shrink: 0;
  margin-left: 10px;
}

.username {
  font-size: 14px;
  color: rgba(255, 255, 255, 0.9);
}

.main-menu {
  flex: 1;
  min-width: 0;
  max-width: calc(100vw - 400px);
  overflow-x: auto;
}

.main-menu .el-menu-item {
  padding: 0 12px;
  font-size: 14px;
}

.main-menu .el-icon {
  margin-right: 4px;
}

.el-main {
  padding: 20px;
}

/* Скрываем scrollbar для menu */
.main-menu::-webkit-scrollbar {
  height: 0;
}

.main-menu {
  scrollbar-width: none;
}
</style>
