// client/src/components/CheckForm.svelte
<script>
  import { checkApi } from '../lib/api.js'

  let loading = false
  let paymentType = 'cash'
  let form = {
    num: '',
    typedoc: 'check',
    hall: '',
    table: '',
    create: new Date().toLocaleString('ru-RU'),
    waiter: '',
    employee_fio: '',
    employee_inn: '',
    employee_pos: '',
    alldiscount: '0',
    products: [{
      name: '',
      kolvo: '1',
      price: '0',
      mark: '0',
      GTIN: '',
      qr: '',
      alc_code: '',
      egais_mark_code: ''
    }]
  }

  function addProduct() {
    form.products = [...form.products, {
      name: '',
      kolvo: 1,
      price: 0,
      mark: '0',
      GTIN: '',
      qr: '',
      alc_code: '',
      egais_mark_code: ''
    }]
  }

  function removeProduct(index) {
    if (form.products.length > 1) {
      form.products = form.products.filter((_, i) => i !== index)
    }
  }

  async function submitCheck() {
    loading = true
    try {
      let result
      if (paymentType === 'cash') {
        result = await checkApi.cashPayment(form)
      } else {
        result = await checkApi.cardPayment(form)
      }
      
      if (result.data.status === 'success') {
        alert('Чек успешно пробит!')
        resetForm()
      } else {
        alert('Ошибка: ' + result.data.message)
      }
    } catch (error) {
      alert('Ошибка: ' + error.message)
    } finally {
      loading = false
    }
  }

  function resetForm() {
    form = {
      num: '',
      typedoc: 'check',
      hall: '',
      table: '',
      create: new Date().toLocaleString('ru-RU'),
      waiter: '',
      employee_fio: '',
      employee_inn: '',
      employee_pos: '',
      alldiscount: '0',
      products: [{
        name: '',
        kolvo: '1',
        price: '0',
        mark: '0',
        GTIN: '',
        qr: '',
        alc_code: '',
        egais_mark_code: ''
      }]
    }
  }
</script>

<div class="card">
  <h2 class="card-header">Пробитие чека</h2>
  
  <form on:submit|preventDefault={submitCheck} class="space-y-4">
    <div class="grid grid-cols-3 gap-4">
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Номер заказа</label>
        <input type="text" class="input" bind:value={form.num} placeholder="Введите номер заказа" />
      </div>
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Тип документа</label>
        <select class="input" bind:value={form.typedoc}>
          <option value="check">Чек</option>
          <option value="return">Возврат</option>
        </select>
      </div>
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Тип оплаты</label>
        <select class="input" bind:value={paymentType}>
          <option value="cash">Наличные</option>
          <option value="card">Карта</option>
        </select>
      </div>
    </div>
    
    <div class="grid grid-cols-3 gap-4">
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Зал</label>
        <input type="text" class="input" bind:value={form.hall} placeholder="Номер зала" />
      </div>
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Стол</label>
        <input type="text" class="input" bind:value={form.table} placeholder="Номер стола" />
      </div>
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Официант</label>
        <input type="text" class="input" bind:value={form.waiter} placeholder="Имя официанта" />
      </div>
    </div>
    
    <div class="grid grid-cols-2 gap-4">
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Сотрудник ФИО</label>
        <input type="text" class="input" bind:value={form.employee_fio} placeholder="ФИО сотрудника" />
      </div>
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">ИНН сотрудника</label>
        <input type="text" class="input" bind:value={form.employee_inn} placeholder="ИНН сотрудника" />
      </div>
    </div>
    
    <div class="grid grid-cols-2 gap-4">
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Должность</label>
        <input type="text" class="input" bind:value={form.employee_pos} placeholder="Должность" />
      </div>
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Общая скидка %</label>
        <input type="number" class="input" bind:value={form.alldiscount} min="0" max="100" />
      </div>
    </div>
    
    <div class="border-t border-gray-200 pt-4 mt-4">
      <h3 class="text-lg font-semibold mb-4">Товары</h3>
      
      {#each form.products as product, index}
        <div class="card mb-4">
          <div class="grid grid-cols-5 gap-4 mb-4">
            <div class="col-span-2">
              <label class="block text-sm font-medium text-gray-700 mb-1">Товар {index + 1}</label>
              <input type="text" class="input" bind:value={product.name} placeholder="Название товара" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Количество</label>
              <input type="number" class="input" bind:value={product.kolvo} min="0.01" step="0.01" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Цена</label>
              <input type="number" class="input" bind:value={product.price} min="0" step="0.01" />
            </div>
            <div class="flex items-end">
              <button
                type="button"
                class="btn btn-danger w-full"
                on:click={() => removeProduct(index)}
              >
                Удалить
              </button>
            </div>
          </div>
          
          <div class="flex items-center gap-2 mb-4">
            <input
              type="checkbox"
              id="mark-{index}"
              checked={product.mark === '1' || product.mark === true}
              on:change={(e) => product.mark = e.target.checked ? '1' : '0'}
              class="w-4 h-4"
            />
            <label for="mark-{index}" class="text-sm font-medium text-gray-700">Маркировка</label>
          </div>
          
          {#if product.mark === '1' || product.mark === true}
            <div class="grid grid-cols-3 gap-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">GTIN</label>
                <input type="text" class="input" bind:value={product.GTIN} placeholder="GTIN код" />
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">QR код</label>
                <input type="text" class="input" bind:value={product.qr} placeholder="QR код маркировки" />
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Алкокод</label>
                <input type="text" class="input" bind:value={product.alc_code} placeholder="Алкокод для ЕГАИС" />
              </div>
            </div>
          {/if}
        </div>
      {/each}
      
      <button type="button" class="btn btn-secondary mb-4" on:click={addProduct}>
        Добавить товар
      </button>
    </div>
    
    <div class="flex gap-3 pt-4 border-t border-gray-200">
      <button type="submit" class="btn btn-primary" disabled={loading}>
        {loading ? 'Обработка...' : 'Пробить чек'}
      </button>
      <button type="button" class="btn btn-secondary" on:click={resetForm}>
        Сбросить
      </button>
    </div>
  </form>
</div>

// client/src/components/CheckForm.vue
<template>
  <div class="check-form">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>Пробитие чека</span>
        </div>
      </template>
      
      <el-form :model="form" label-width="120px" @submit.prevent="submitCheck">
        <el-row :gutter="20">
          <el-col :span="8">
            <el-form-item label="Номер заказа">
              <el-input v-model="form.num" placeholder="Введите номер заказа" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="Тип документа">
              <el-select v-model="form.typedoc" placeholder="Тип документа">
                <el-option label="Чек" value="check" />
                <el-option label="Возврат" value="return" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="Тип оплаты">
              <el-select v-model="paymentType" placeholder="Выберите тип оплаты">
                <el-option label="Наличные" value="cash" />
                <el-option label="Карта" value="card" />
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>
        
        <el-row :gutter="20">
          <el-col :span="8">
            <el-form-item label="Зал">
              <el-input v-model="form.hall" placeholder="Номер зала" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="Стол">
              <el-input v-model="form.table" placeholder="Номер стола" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="Официант">
              <el-input v-model="form.waiter" placeholder="Имя официанта" />
            </el-form-item>
          </el-col>
        </el-row>
        
        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="Сотрудник ФИО">
              <el-input v-model="form.employee_fio" placeholder="ФИО сотрудника" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="ИНН сотрудника">
              <el-input v-model="form.employee_inn" placeholder="ИНН сотрудника" />
            </el-form-item>
          </el-col>
        </el-row>
        
        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="Должность">
              <el-input v-model="form.employee_pos" placeholder="Должность" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="Общая скидка %">
              <el-input-number v-model="form.alldiscount" :min="0" :max="100" />
            </el-form-item>
          </el-col>
        </el-row>
        
        <el-divider content-position="left">Товары</el-divider>
        
        <div v-for="(item, index) in form.products" :key="index" class="product-item">
          <el-card>
            <el-row :gutter="10">
              <el-col :span="8">
                <el-form-item :label="`Товар ${index + 1}`">
                  <el-input v-model="item.name" placeholder="Название товара" />
                </el-form-item>
              </el-col>
              <el-col :span="4">
                <el-form-item label="Количество">
                  <el-input-number v-model="item.kolvo" :min="0.01" :precision="2" @change="item.kolvo = String(item.kolvo)" />
                </el-form-item>
              </el-col>
              <el-col :span="4">
                <el-form-item label="Цена">
                  <el-input-number v-model="item.price" :min="0" :precision="2" @change="item.price = String(item.price)" />
                </el-form-item>
              </el-col>
              <el-col :span="4">
                <el-form-item label="Маркировка">
                  <el-switch v-model="item.mark" active-value="1" inactive-value="0" />
                </el-form-item>
              </el-col>
              <el-col :span="4">
                <el-button type="danger" @click="removeProduct(index)">Удалить</el-button>
              </el-col>
            </el-row>
            
            <el-row v-if="item.mark === '1'" :gutter="10">
              <el-col :span="8">
                <el-form-item label="GTIN">
                  <el-input v-model="item.GTIN" placeholder="GTIN код" />
                </el-form-item>
              </el-col>
              <el-col :span="8">
                <el-form-item label="QR код">
                  <el-input v-model="item.qr" placeholder="QR код маркировки" />
                </el-form-item>
              </el-col>
              <el-col :span="8">
                <el-form-item label="Алкокод">
                  <el-input v-model="item.alc_code" placeholder="Алкокод для ЕГАИС" />
                </el-form-item>
              </el-col>
            </el-row>
          </el-card>
        </div>
        
        <el-button type="primary" @click="addProduct">Добавить товар</el-button>
        
        <el-divider />
        
        <el-form-item>
          <el-button type="primary" @click="submitCheck" :loading="loading">
            Пробить чек
          </el-button>
          <el-button @click="resetForm">Сбросить</el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </div>
</template>

<script>
import { checkApi } from '../api'

export default {
  name: 'CheckForm',
  data() {
    return {
      loading: false,
      paymentType: 'cash',
      form: {
        num: '',
        typedoc: 'check',
        hall: '',
        table: '',
        create: new Date().toLocaleString('ru-RU'),
        waiter: '',
        employee_fio: '',
        employee_inn: '',
        employee_pos: '',
        alldiscount: '0',
        products: [
          {
            name: '',
            kolvo: '1',
            price: '0',
            mark: '0',
            GTIN: '',
            qr: '',
            alc_code: '',
            egais_mark_code: ''
          }
        ]
      }
    }
  },
  methods: {
    addProduct() {
      this.form.products.push({
        name: '',
        kolvo: 1,
        price: 0,
        mark: '0',
        GTIN: '',
        qr: '',
        alc_code: '',
        egais_mark_code: ''
      })
    },
    removeProduct(index) {
      if (this.form.products.length > 1) {
        this.form.products.splice(index, 1)
      }
    },
    async submitCheck() {
      this.loading = true
      try {
        let result
        if (this.paymentType === 'cash') {
          result = await checkApi.cashPayment(this.form)
        } else {
          result = await checkApi.cardPayment(this.form)
        }
        
        if (result.data.status === 'success') {
          this.$message.success('Чек успешно пробит!')
          this.$emit('check-created', result.data)
        } else {
          this.$message.error('Ошибка: ' + result.data.message)
        }
      } catch (error) {
        this.$message.error('Ошибка: ' + error.message)
      } finally {
        this.loading = false
      }
    },
    resetForm() {
      this.form = {
        num: '',
        typedoc: 'check',
        hall: '',
        table: '',
        create: new Date().toLocaleString('ru-RU'),
        waiter: '',
        employee_fio: '',
        employee_inn: '',
        employee_pos: '',
        alldiscount: '0',
        products: [
          {
            name: '',
            kolvo: '1',
            price: '0',
            mark: '0',
            GTIN: '',
            qr: '',
            alc_code: '',
            egais_mark_code: ''
          }
        ]
      }
    }
  }
}
</script>

<style scoped>
.product-item {
  margin-bottom: 10px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>
