// client/src/components/EgaisForm.vue
<template>
  <div class="egais-form">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>Отправка в ЕГАИС</span>
        </div>
      </template>
      
      <el-form :model="form" label-width="120px" @submit.prevent="submitEgais">
        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="Номер заказа">
              <el-input v-model="form.num" placeholder="Введите номер заказа" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="Сотрудник ФИО">
              <el-input v-model="form.employee_fio" placeholder="ФИО сотрудника" />
            </el-form-item>
          </el-col>
        </el-row>
        
        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="ИНН сотрудника">
              <el-input v-model="form.employee_inn" placeholder="ИНН сотрудника" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="Должность">
              <el-input v-model="form.employee_pos" placeholder="Должность" />
            </el-form-item>
          </el-col>
        </el-row>
        
        <el-divider content-position="left">Алкогольные товары</el-divider>
        
        <div v-for="(item, index) in form.products" :key="index" class="product-item">
          <el-card>
            <el-row :gutter="10">
              <el-col :span="6">
                <el-form-item :label="`Товар ${index + 1}`">
                  <el-input v-model="item.name" placeholder="Название товара" />
                </el-form-item>
              </el-col>
              <el-col :span="4">
                <el-form-item label="Количество">
                  <el-input-number v-model="item.kolvo" :min="0.01" :precision="2" @change="item.kolvo = String(item.kolvo)" />
                </el-form-item>
              </el-col>
              <el-col :span="4">
                <el-form-item label="Цена">
                  <el-input-number v-model="item.price" :min="0" :precision="2" @change="item.price = String(item.price)" />
                </el-form-item>
              </el-col>
              <el-col :span="4">
                <el-form-item label="GTIN">
                  <el-input v-model="item.GTIN" placeholder="GTIN код" />
                </el-form-item>
              </el-col>
              <el-col :span="4">
                <el-form-item label="Алкокод">
                  <el-input v-model="item.alc_code" placeholder="Алкокод" />
                </el-form-item>
              </el-col>
              <el-col :span="2">
                <el-button type="danger" @click="removeProduct(index)">×</el-button>
              </el-col>
            </el-row>
            
            <el-row :gutter="10">
              <el-col :span="8">
                <el-form-item label="QR код маркировки">
                  <el-input v-model="item.qr" placeholder="QR код маркировки" />
                </el-form-item>
              </el-col>
              <el-col :span="8">
                <el-form-item label="Код марки ЕГАИС">
                  <el-input v-model="item.egais_mark_code" placeholder="Код марки для ЕГАИС" />
                </el-form-item>
              </el-col>
              <el-col :span="8">
                <el-form-item label="ID ЕГАИС">
                  <el-input v-model="item.egais_id" placeholder="Идентификатор ЕГАИС" />
                </el-form-item>
              </el-col>
            </el-row>
          </el-card>
        </div>
        
        <el-button type="primary" @click="addProduct">Добавить алкогольный товар</el-button>
        
        <el-divider />
        
        <el-form-item>
          <el-button type="primary" @click="submitEgais" :loading="loading">
            Отправить в ЕГАИС
          </el-button>
          <el-button @click="resetForm">Сбросить</el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </div>
</template>

<script>
import { egaisApi } from '../api'

export default {
  name: 'EgaisForm',
  data() {
    return {
      loading: false,
      form: {
        num: '',
        typedoc: 'check',
        hall: '',
        table: '',
        create: new Date().toLocaleString('ru-RU'),
        waiter: '',
        employee_fio: '',
        employee_inn: '',
        employee_pos: '',
        alldiscount: '0',
        products: [
          {
            name: '',
            kolvo: '1',
            price: '0',
            GTIN: '',
            alc_code: '',
            qr: '',
            egais_mark_code: '',
            egais_id: '',
            mark: '1' // Всегда маркированные для ЕГАИС
          }
        ]
      }
    }
  },
  methods: {
    addProduct() {
      this.form.products.push({
        name: '',
        kolvo: 1,
        price: 0,
        GTIN: '',
        alc_code: '',
        qr: '',
        egais_mark_code: '',
        egais_id: '',
        mark: '1'
      })
    },
    removeProduct(index) {
      if (this.form.products.length > 1) {
        this.form.products.splice(index, 1)
      }
    },
    async submitEgais() {
      this.loading = true
      try {
        const result = await egaisApi.sendCheck(this.form)
        
        if (result.data.message) {
          this.$message.success('ЕГАИС: ' + result.data.message)
          this.$emit('egais-sent', result.data)
        } else if (result.data.error) {
          this.$message.error('Ошибка: ' + result.data.error)
        }
      } catch (error) {
        this.$message.error('Ошибка: ' + error.message)
      } finally {
        this.loading = false
      }
    },
    resetForm() {
      this.form = {
        num: '',
        typedoc: 'check',
        hall: '',
        table: '',
        create: new Date().toLocaleString('ru-RU'),
        waiter: '',
        employee_fio: '',
        employee_inn: '',
        employee_pos: '',
        alldiscount: '0',
        products: [
          {
            name: '',
            kolvo: '1',
            price: '0',
            GTIN: '',
            alc_code: '',
            qr: '',
            egais_mark_code: '',
            egais_id: '',
            mark: '1'
          }
        ]
      }
    }
  }
}
</script>

<style scoped>
.product-item {
  margin-bottom: 10px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>

// client/src/components/EgaisForm.svelte
<script>
  import { egaisApi } from '../lib/api.js'

  let loading = false
  let form = {
    num: '',
    typedoc: 'check',
    hall: '',
    table: '',
    create: new Date().toLocaleString('ru-RU'),
    waiter: '',
    employee_fio: '',
    employee_inn: '',
    employee_pos: '',
    alldiscount: '0',
    products: [{
      name: '',
      kolvo: '1',
      price: '0',
      GTIN: '',
      alc_code: '',
      qr: '',
      egais_mark_code: '',
      egais_id: '',
      mark: '1'
    }]
  }

  function addProduct() {
    form.products = [...form.products, {
      name: '',
      kolvo: 1,
      price: 0,
      GTIN: '',
      alc_code: '',
      qr: '',
      egais_mark_code: '',
      egais_id: '',
      mark: '1'
    }]
  }

  function removeProduct(index) {
    if (form.products.length > 1) {
      form.products = form.products.filter((_, i) => i !== index)
    }
  }

  async function submitEgais() {
    loading = true
    try {
      const result = await egaisApi.sendCheck(form)
      
      if (result.data.message) {
        alert('ЕГАИС: ' + result.data.message)
        resetForm()
      } else if (result.data.error) {
        alert('Ошибка: ' + result.data.error)
      }
    } catch (error) {
      alert('Ошибка: ' + error.message)
    } finally {
      loading = false
    }
  }

  function resetForm() {
    form = {
      num: '',
      typedoc: 'check',
      hall: '',
      table: '',
      create: new Date().toLocaleString('ru-RU'),
      waiter: '',
      employee_fio: '',
      employee_inn: '',
      employee_pos: '',
      alldiscount: '0',
      products: [{
        name: '',
        kolvo: '1',
        price: '0',
        GTIN: '',
        alc_code: '',
        qr: '',
        egais_mark_code: '',
        egais_id: '',
        mark: '1'
      }]
    }
  }
</script>

<div class="card">
  <h2 class="card-header">Отправка в ЕГАИС</h2>
  
  <form on:submit|preventDefault={submitEgais} class="space-y-4">
    <div class="grid grid-cols-2 gap-4">
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Номер заказа</label>
        <input type="text" class="input" bind:value={form.num} placeholder="Введите номер заказа" />
      </div>
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Сотрудник ФИО</label>
        <input type="text" class="input" bind:value={form.employee_fio} placeholder="ФИО сотрудника" />
      </div>
    </div>
    
    <div class="grid grid-cols-2 gap-4">
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">ИНН сотрудника</label>
        <input type="text" class="input" bind:value={form.employee_inn} placeholder="ИНН сотрудника" />
      </div>
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Должность</label>
        <input type="text" class="input" bind:value={form.employee_pos} placeholder="Должность" />
      </div>
    </div>
    
    <div class="border-t border-gray-200 pt-4 mt-4">
      <h3 class="text-lg font-semibold mb-4">Алкогольные товары</h3>
      
      {#each form.products as product, index}
        <div class="card mb-4">
          <div class="grid grid-cols-6 gap-4 mb-4">
            <div class="col-span-2">
              <label class="block text-sm font-medium text-gray-700 mb-1">Товар {index + 1}</label>
              <input type="text" class="input" bind:value={product.name} placeholder="Название товара" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Количество</label>
              <input type="number" class="input" bind:value={product.kolvo} min="0.01" step="0.01" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Цена</label>
              <input type="number" class="input" bind:value={product.price} min="0" step="0.01" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">GTIN</label>
              <input type="text" class="input" bind:value={product.GTIN} placeholder="GTIN код" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Алкокод</label>
              <input type="text" class="input" bind:value={product.alc_code} placeholder="Алкокод" />
            </div>
            <div class="flex items-end">
              <button
                type="button"
                class="btn btn-danger w-full"
                on:click={() => removeProduct(index)}
              >
                ×
              </button>
            </div>
          </div>
          
          <div class="grid grid-cols-3 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">QR код маркировки</label>
              <input type="text" class="input" bind:value={product.qr} placeholder="QR код маркировки" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Код марки ЕГАИС</label>
              <input type="text" class="input" bind:value={product.egais_mark_code} placeholder="Код марки для ЕГАИС" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">ID ЕГАИС</label>
              <input type="text" class="input" bind:value={product.egais_id} placeholder="Идентификатор ЕГАИС" />
            </div>
          </div>
        </div>
      {/each}
      
      <button type="button" class="btn btn-secondary mb-4" on:click={addProduct}>
        Добавить алкогольный товар
      </button>
    </div>
    
    <div class="flex gap-3 pt-4 border-t border-gray-200">
      <button type="submit" class="btn btn-primary" disabled={loading}>
        {loading ? 'Отправка...' : 'Отправить в ЕГАИС'}
      </button>
      <button type="button" class="btn btn-secondary" on:click={resetForm}>
        Сбросить
      </button>
    </div>
  </form>
</div>
