// client/src/components/LogsView.svelte
<script>
    import { logsApi } from "../lib/api.js";
    import { onMount } from "svelte";

    let activeTab = "checks";
    let checkLogs = [];
    let checkLoading = false;
    let checkPage = 1;
    let checkPageSize = 20;
    let checkTotal = 0;
    let checkStatus = "";

    let egaisLogs = [];
    let egaisLoading = false;
    let egaisPage = 1;
    let egaisPageSize = 20;
    let egaisTotal = 0;
    let egaisStatus = "";

    let detailsVisible = false;
    let detailsTitle = "";
    let detailsContent = "";

    onMount(() => {
        loadCheckLogs();
    });

    async function loadCheckLogs() {
        checkLoading = true;
        try {
            const params = {
                page: checkPage,
                limit: checkPageSize,
            };
            if (checkStatus) {
                params.status = checkStatus;
            }

            const result = await logsApi.getCheckLogs(params);
            if (result.data.status === "success") {
                checkLogs = result.data.data;
                checkTotal = result.data.pagination.total;
            }
        } catch (error) {
            alert("Ошибка: " + error.message);
        } finally {
            checkLoading = false;
        }
    }

    async function loadEgaisLogs() {
        egaisLoading = true;
        try {
            const params = {
                page: egaisPage,
                limit: egaisPageSize,
            };
            if (egaisStatus) {
                params.status = egaisStatus;
            }

            const result = await logsApi.getEgaisLogs(params);
            if (result.data.status === "success") {
                egaisLogs = result.data.data;
                egaisTotal = result.data.pagination.total;
            }
        } catch (error) {
            alert("Ошибка: " + error.message);
        } finally {
            egaisLoading = false;
        }
    }

    function handleTabClick(tab) {
        activeTab = tab;
        if (tab === "egais" && egaisLogs.length === 0) {
            loadEgaisLogs();
        }
    }

    function viewCheckDetails(row) {
        detailsTitle = `Детали чека #${row.id}`;
        detailsContent = JSON.stringify(row, null, 2);
        detailsVisible = true;
    }

    function viewEgaisDetails(row) {
        detailsTitle = `Детали ЕГАИС #${row.id}`;
        detailsContent = JSON.stringify(row, null, 2);
        detailsVisible = true;
    }

    function refreshLogs() {
        if (activeTab === "checks") {
            loadCheckLogs();
        } else {
            loadEgaisLogs();
        }
    }

    function formatDate(dateString) {
        return new Date(dateString).toLocaleString("ru-RU");
    }

    function getStatusType(status) {
        switch (status) {
            case "success":
                return "bg-success-100 text-success-700";
            case "error":
                return "bg-danger-100 text-danger-700";
            case "saved":
                return "bg-warning-100 text-warning-700";
            default:
                return "bg-gray-100 text-gray-700";
        }
    }
</script>

<div class="card">
    <div class="flex justify-between items-center mb-4">
        <h2 class="text-xl font-semibold">Просмотр логов</h2>
        <button class="btn btn-primary" on:click={refreshLogs}>
            Обновить
        </button>
    </div>

    <div class="border-b border-gray-200 mb-4">
        <div class="flex gap-4">
            <button
                class="px-4 py-2 border-b-2 transition-colors {activeTab ===
                'checks'
                    ? 'border-primary-500 text-primary-500'
                    : 'border-transparent text-gray-600 hover:text-gray-900'}"
                on:click={() => handleTabClick("checks")}
            >
                Логи чеков
            </button>
            <button
                class="px-4 py-2 border-b-2 transition-colors {activeTab ===
                'egais'
                    ? 'border-primary-500 text-primary-500'
                    : 'border-transparent text-gray-600 hover:text-gray-900'}"
                on:click={() => handleTabClick("egais")}
            >
                Логи ЕГАИС
            </button>
        </div>
    </div>

    {#if activeTab === "checks"}
        <div class="space-y-4">
            <div class="flex gap-4 items-center">
                <select
                    class="input w-auto"
                    bind:value={checkStatus}
                    on:change={loadCheckLogs}
                >
                    <option value="">Все</option>
                    <option value="success">Успешно</option>
                    <option value="error">Ошибка</option>
                </select>
                <input
                    type="number"
                    class="input w-24"
                    bind:value={checkPageSize}
                    min="10"
                    max="100"
                    on:change={loadCheckLogs}
                />
            </div>

            {#if checkLoading}
                <div class="text-center py-8">Загрузка...</div>
            {:else}
                <div class="overflow-x-auto">
                    <table class="w-full border-collapse">
                        <thead>
                            <tr class="bg-gray-100">
                                <th
                                    class="border border-gray-300 px-4 py-2 text-left"
                                    >ID</th
                                >
                                <th
                                    class="border border-gray-300 px-4 py-2 text-left"
                                    >Время</th
                                >
                                <th
                                    class="border border-gray-300 px-4 py-2 text-left"
                                    >Статус</th
                                >
                                <th
                                    class="border border-gray-300 px-4 py-2 text-left"
                                    >Сообщение</th
                                >
                                <th
                                    class="border border-gray-300 px-4 py-2 text-left"
                                    >Код результата</th
                                >
                                <th
                                    class="border border-gray-300 px-4 py-2 text-left"
                                    >Номер чека</th
                                >
                                <th
                                    class="border border-gray-300 px-4 py-2 text-left"
                                    >Фискальный признак</th
                                >
                                <th
                                    class="border border-gray-300 px-4 py-2 text-left"
                                    >Действия</th
                                >
                            </tr>
                        </thead>
                        <tbody>
                            {#each checkLogs as log}
                                <tr class="hover:bg-gray-50">
                                    <td class="border border-gray-300 px-4 py-2"
                                        >{log.id}</td
                                    >
                                    <td class="border border-gray-300 px-4 py-2"
                                        >{formatDate(log.timestamp)}</td
                                    >
                                    <td
                                        class="border border-gray-300 px-4 py-2"
                                    >
                                        <span
                                            class="px-2 py-1 rounded text-sm {getStatusType(
                                                log.status,
                                            )}"
                                        >
                                            {log.status}
                                        </span>
                                    </td>
                                    <td class="border border-gray-300 px-4 py-2"
                                        >{log.message}</td
                                    >
                                    <td class="border border-gray-300 px-4 py-2"
                                        >{log.result_code || "-"}</td
                                    >
                                    <td class="border border-gray-300 px-4 py-2"
                                        >{log.document_number || "-"}</td
                                    >
                                    <td
                                        class="border border-gray-300 px-4 py-2"
                                    >
                                        {#if log.fiscal_sign}
                                            <span
                                                class="font-mono text-xs bg-primary-50 text-primary-700 px-2 py-1 rounded"
                                            >
                                                {log.fiscal_sign}
                                            </span>
                                        {:else}
                                            <span class="text-gray-400 italic"
                                                >-</span
                                            >
                                        {/if}
                                    </td>
                                    <td
                                        class="border border-gray-300 px-4 py-2"
                                    >
                                        <button
                                            class="btn btn-secondary text-sm"
                                            on:click={() =>
                                                viewCheckDetails(log)}
                                            >Детали</button
                                        >
                                    </td>
                                </tr>
                            {/each}
                        </tbody>
                    </table>
                </div>

                {#if checkTotal > 0}
                    <div class="flex justify-between items-center">
                        <div class="text-sm text-gray-600">
                            Показано {(checkPage - 1) * checkPageSize + 1} - {Math.min(
                                checkPage * checkPageSize,
                                checkTotal,
                            )} из {checkTotal}
                        </div>
                        <div class="flex gap-2">
                            <button
                                class="btn btn-secondary text-sm"
                                disabled={checkPage === 1}
                                on:click={() => {
                                    checkPage--;
                                    loadCheckLogs();
                                }}
                            >
                                Назад
                            </button>
                            <button
                                class="btn btn-secondary text-sm"
                                disabled={checkPage * checkPageSize >=
                                    checkTotal}
                                on:click={() => {
                                    checkPage++;
                                    loadCheckLogs();
                                }}
                            >
                                Вперед
                            </button>
                        </div>
                    </div>
                {/if}
            {/if}
        </div>
    {:else}
        <div class="space-y-4">
            <div class="flex gap-4 items-center">
                <select
                    class="input w-auto"
                    bind:value={egaisStatus}
                    on:change={loadEgaisLogs}
                >
                    <option value="">Все</option>
                    <option value="success">Успешно</option>
                    <option value="error">Ошибка</option>
                    <option value="saved">Сохранено</option>
                </select>
                <input
                    type="number"
                    class="input w-24"
                    bind:value={egaisPageSize}
                    min="10"
                    max="100"
                    on:change={loadEgaisLogs}
                />
            </div>

            {#if egaisLoading}
                <div class="text-center py-8">Загрузка...</div>
            {:else}
                <div class="overflow-x-auto">
                    <table class="w-full border-collapse">
                        <thead>
                            <tr class="bg-gray-100">
                                <th
                                    class="border border-gray-300 px-4 py-2 text-left"
                                    >ID</th
                                >
                                <th
                                    class="border border-gray-300 px-4 py-2 text-left"
                                    >Время</th
                                >
                                <th
                                    class="border border-gray-300 px-4 py-2 text-left"
                                    >Статус</th
                                >
                                <th
                                    class="border border-gray-300 px-4 py-2 text-left"
                                    >QR код</th
                                >
                                <th
                                    class="border border-gray-300 px-4 py-2 text-left"
                                    >Подпись</th
                                >
                                <th
                                    class="border border-gray-300 px-4 py-2 text-left"
                                    >Действия</th
                                >
                            </tr>
                        </thead>
                        <tbody>
                            {#each egaisLogs as log}
                                <tr class="hover:bg-gray-50">
                                    <td class="border border-gray-300 px-4 py-2"
                                        >{log.id}</td
                                    >
                                    <td class="border border-gray-300 px-4 py-2"
                                        >{formatDate(log.timestamp)}</td
                                    >
                                    <td
                                        class="border border-gray-300 px-4 py-2"
                                    >
                                        <span
                                            class="px-2 py-1 rounded text-sm {getStatusType(
                                                log.status,
                                            )}"
                                        >
                                            {log.status}
                                        </span>
                                    </td>
                                    <td
                                        class="border border-gray-300 px-4 py-2"
                                    >
                                        {#if log.qr_code}
                                            <span class="font-mono text-xs"
                                                >{log.qr_code.substring(
                                                    0,
                                                    15,
                                                )}...</span
                                            >
                                        {:else}
                                            <span class="text-gray-400 italic"
                                                >-</span
                                            >
                                        {/if}
                                    </td>
                                    <td
                                        class="border border-gray-300 px-4 py-2"
                                    >
                                        {#if log.sign}
                                            <span
                                                class="font-mono text-xs bg-warning-50 text-warning-700 px-2 py-1 rounded"
                                            >
                                                {log.sign.substring(0, 12)}...
                                            </span>
                                        {:else}
                                            <span class="text-gray-400 italic"
                                                >-</span
                                            >
                                        {/if}
                                    </td>
                                    <td
                                        class="border border-gray-300 px-4 py-2"
                                    >
                                        <button
                                            class="btn btn-secondary text-sm"
                                            on:click={() =>
                                                viewEgaisDetails(log)}
                                            >Детали</button
                                        >
                                    </td>
                                </tr>
                            {/each}
                        </tbody>
                    </table>
                </div>

                {#if egaisTotal > 0}
                    <div class="flex justify-between items-center">
                        <div class="text-sm text-gray-600">
                            Показано {(egaisPage - 1) * egaisPageSize + 1} - {Math.min(
                                egaisPage * egaisPageSize,
                                egaisTotal,
                            )} из {egaisTotal}
                        </div>
                        <div class="flex gap-2">
                            <button
                                class="btn btn-secondary text-sm"
                                disabled={egaisPage === 1}
                                on:click={() => {
                                    egaisPage--;
                                    loadEgaisLogs();
                                }}
                            >
                                Назад
                            </button>
                            <button
                                class="btn btn-secondary text-sm"
                                disabled={egaisPage * egaisPageSize >=
                                    egaisTotal}
                                on:click={() => {
                                    egaisPage++;
                                    loadEgaisLogs();
                                }}
                            >
                                Вперед
                            </button>
                        </div>
                    </div>
                {/if}
            {/if}
        </div>
    {/if}
</div>

<!-- Диалог деталей -->
{#if detailsVisible}
    <div
        class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
    >
        <div class="card w-full max-w-4xl max-h-[80vh] overflow-y-auto">
            <div class="flex justify-between items-center mb-4">
                <h3 class="text-lg font-semibold">{detailsTitle}</h3>
                <button
                    class="btn btn-secondary"
                    on:click={() => (detailsVisible = false)}>Закрыть</button
                >
            </div>
            <pre
                class="bg-gray-100 p-4 rounded overflow-x-auto text-sm">{detailsContent}</pre>
        </div>
    </div>
{/if}

// client/src/components/LogsView.vue
<template>
  <div class="logs-view">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>Просмотр логов</span>
          <el-button @click="refreshLogs">Обновить</el-button>
        </div>
      </template>
      
      <el-tabs v-model="activeTab" @tab-click="handleTabClick">
        <el-tab-pane label="Логи чеков" name="checks">
          <div class="filters">
            <el-select v-model="checkStatus" placeholder="Статус" @change="loadCheckLogs">
              <el-option label="Все" value="" />
              <el-option label="Успешно" value="success" />
              <el-option label="Ошибка" value="error" />
            </el-select>
            <el-input-number v-model="checkPageSize" :min="10" :max="100" @change="loadCheckLogs" />
          </div>
          
          <el-table :data="checkLogs" v-loading="checkLoading" stripe>
            <el-table-column prop="id" label="ID" width="80" />
            <el-table-column prop="timestamp" label="Время" width="180">
              <template #default="scope">
                {{ formatDate(scope.row.timestamp) }}
              </template>
            </el-table-column>
            <el-table-column prop="status" label="Статус" width="100">
              <template #default="scope">
                <el-tag :type="scope.row.status === 'success' ? 'success' : 'danger'">
                  {{ scope.row.status }}
                </el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="message" label="Сообщение" />
            <el-table-column prop="result_code" label="Код результата" width="120" />
            <el-table-column prop="document_number" label="Номер чека" width="120">
              <template #default="scope">
                <span v-if="scope.row.document_number">{{ scope.row.document_number }}</span>
                <span v-else class="text-muted">-</span>
              </template>
            </el-table-column>
            <el-table-column prop="fiscal_sign" label="Фискальный признак" width="150">
              <template #default="scope">
                <span v-if="scope.row.fiscal_sign" class="fiscal-sign">{{ scope.row.fiscal_sign }}</span>
                <span v-else class="text-muted">-</span>
              </template>
            </el-table-column>
            <el-table-column label="Действия" width="100">
              <template #default="scope">
                <el-button size="small" @click="viewCheckDetails(scope.row)">Детали</el-button>
              </template>
            </el-table-column>
          </el-table>
          
          <el-pagination
            v-model:current-page="checkPage"
            :page-size="checkPageSize"
            :total="checkTotal"
            @current-change="loadCheckLogs"
            layout="total, prev, pager, next"
          />
        </el-tab-pane>
        
        <el-tab-pane label="Логи ЕГАИС" name="egais">
          <div class="filters">
            <el-select v-model="egaisStatus" placeholder="Статус" @change="loadEgaisLogs">
              <el-option label="Все" value="" />
              <el-option label="Успешно" value="success" />
              <el-option label="Ошибка" value="error" />
              <el-option label="Сохранено" value="saved" />
            </el-select>
            <el-input-number v-model="egaisPageSize" :min="10" :max="100" @change="loadEgaisLogs" />
          </div>
          
          <el-table :data="egaisLogs" v-loading="egaisLoading" stripe>
            <el-table-column prop="id" label="ID" width="80" />
            <el-table-column prop="timestamp" label="Время" width="180">
              <template #default="scope">
                {{ formatDate(scope.row.timestamp) }}
              </template>
            </el-table-column>
            <el-table-column prop="status" label="Статус" width="100">
              <template #default="scope">
                <el-tag :type="getStatusType(scope.row.status)">
                  {{ scope.row.status }}
                </el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="qr_code" label="QR код" width="200">
              <template #default="scope">
                <span v-if="scope.row.qr_code" class="qr-code">{{ scope.row.qr_code.substring(0, 20) }}...</span>
                <span v-else>-</span>
              </template>
            </el-table-column>
            <el-table-column label="Действия" width="100">
              <template #default="scope">
                <el-button size="small" @click="viewEgaisDetails(scope.row)">Детали</el-button>
              </template>
            </el-table-column>
          </el-table>
          
          <el-pagination
            v-model:current-page="egaisPage"
            :page-size="egaisPageSize"
            :total="egaisTotal"
            @current-change="loadEgaisLogs"
            layout="total, prev, pager, next"
          />
        </el-tab-pane>
      </el-tabs>
    </el-card>
    
    <!-- Диалог деталей -->
    <el-dialog v-model="detailsVisible" :title="detailsTitle" width="80%">
      <pre class="details-content">{{ detailsContent }}</pre>
    </el-dialog>
  </div>
</template>

<script>
import { logsApi } from '../api'

export default {
  name: 'LogsView',
  data() {
    return {
      activeTab: 'checks',
      checkLogs: [],
      checkLoading: false,
      checkPage: 1,
      checkPageSize: 20,
      checkTotal: 0,
      checkStatus: '',
      egaisLogs: [],
      egaisLoading: false,
      egaisPage: 1,
      egaisPageSize: 20,
      egaisTotal: 0,
      egaisStatus: '',
      detailsVisible: false,
      detailsTitle: '',
      detailsContent: ''
    }
  },
  mounted() {
    this.loadCheckLogs()
  },
  methods: {
    async loadCheckLogs() {
      this.checkLoading = true
      try {
        const params = {
          page: this.checkPage,
          limit: this.checkPageSize
        }
        if (this.checkStatus) {
          params.status = this.checkStatus
        }
        
        const result = await logsApi.getCheckLogs(params)
        if (result.data.status === 'success') {
          this.checkLogs = result.data.data
          this.checkTotal = result.data.pagination.total
        } else {
          this.$message.error('Ошибка загрузки логов чеков')
        }
      } catch (error) {
        this.$message.error('Ошибка: ' + error.message)
      } finally {
        this.checkLoading = false
      }
    },
    
    async loadEgaisLogs() {
      this.egaisLoading = true
      try {
        const params = {
          page: this.egaisPage,
          limit: this.egaisPageSize
        }
        if (this.egaisStatus) {
          params.status = this.egaisStatus
        }
        
        const result = await logsApi.getEgaisLogs(params)
        if (result.data.status === 'success') {
          this.egaisLogs = result.data.data
          this.egaisTotal = result.data.pagination.total
        } else {
          this.$message.error('Ошибка загрузки логов ЕГАИС')
        }
      } catch (error) {
        this.$message.error('Ошибка: ' + error.message)
      } finally {
        this.egaisLoading = false
      }
    },
    
    handleTabClick(tab) {
      if (tab.name === 'egais' && this.egaisLogs.length === 0) {
        this.loadEgaisLogs()
      }
    },
    
    viewCheckDetails(row) {
      this.detailsTitle = `Детали чека #${row.id}`
      this.detailsContent = JSON.stringify(row, null, 2)
      this.detailsVisible = true
    },
    
    viewEgaisDetails(row) {
      this.detailsTitle = `Детали ЕГАИС #${row.id}`
      this.detailsContent = JSON.stringify(row, null, 2)
      this.detailsVisible = true
    },
    
    refreshLogs() {
      if (this.activeTab === 'checks') {
        this.loadCheckLogs()
      } else {
        this.loadEgaisLogs()
      }
    },
    
    formatDate(dateString) {
      return new Date(dateString).toLocaleString('ru-RU')
    },
    
    getStatusType(status) {
      switch (status) {
        case 'success': return 'success'
        case 'error': return 'danger'
        case 'saved': return 'warning'
        default: return 'info'
      }
    }
  }
}
</script>

<style scoped>
.filters {
  margin-bottom: 20px;
  display: flex;
  gap: 10px;
  align-items: center;
}

.details-content {
  background: #f5f5f5;
  padding: 15px;
  border-radius: 4px;
  max-height: 400px;
  overflow-y: auto;
}

.qr-code {
  font-family: monospace;
  font-size: 12px;
}

.fiscal-sign {
  font-family: monospace;
  font-size: 11px;
  color: #409eff;
  background: #f0f9ff;
  padding: 2px 6px;
  border-radius: 3px;
}

.text-muted {
  color: #909399;
  font-style: italic;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>
