// client/src/components/ProductsView.vue
<template>
  <div>
    <el-row :gutter="20">
      <!-- Управление категориями -->
      <el-col :span="6">
        <el-card header="Категории">
            <el-button @click="addCategory" type="primary" size="small" style="width: 100%; margin-bottom: 10px;">
            <el-icon><Plus /></el-icon> Добавить категорию
          </el-button>
          
          <el-tree
            :data="categoriesTree"
            :props="{ children: 'children', label: 'name' }"
            node-key="id"
            @node-click="selectCategory"
            highlight-current
          >
            <template #default="{ node, data }">
              <span class="custom-tree-node">
              <span>{{ node.label }}</span>
              <span>
                <el-button
                  type="text"
                  size="mini"
                  @click.stop="editCategory(data)"
                >
                  <el-icon><Edit /></el-icon>
                </el-button>
                <el-button
                  type="text"
                  size="mini"
                  @click.stop="deleteCategory(data)"
                >
                  <el-icon><Delete /></el-icon>
                </el-button>
              </span>
              </span>
            </template>
          </el-tree>
        </el-card>
      </el-col>

      <!-- Список товаров -->
      <el-col :span="18">
        <el-card>
          <template #header>
            <div class="clearfix">
            <span>Товары</span>
            <div style="float: right;">
              <el-button 
                style="padding: 3px 0; margin-right: 10px;" 
                type="text" 
                @click="refresh"
              >
                <el-icon><Refresh /></el-icon> Обновить
              </el-button>
              <el-button 
                style="padding: 3px 0" 
                type="text" 
                @click="addProduct"
              >
                <el-icon><Plus /></el-icon> Добавить товар
              </el-button>
            </div>
            </div>
          </template>

          <el-table :data="products" v-loading="loading" style="width: 100%">
            <el-table-column prop="name" label="Название" width="200" />
            <el-table-column prop="price" label="Цена" width="100">
              <template #default="scope">
                {{ scope.row.price }} Р
              </template>
            </el-table-column>
            <el-table-column prop="barcode" label="Штрихкод" width="120" />
            <el-table-column prop="unit" label="Ед. изм." width="80" />
            <el-table-column label="Особенности" width="120">
              <template #default="scope">
                <el-tag v-if="scope.row.is_alcohol" size="mini" type="warning">Алко</el-tag>
                <el-tag v-if="scope.row.is_marked" size="mini" type="danger">Марк.</el-tag>
                <el-tag v-if="scope.row.is_draught" size="mini" type="info">Разл.</el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="max_discount" label="Макс. скидка" width="100">
              <template #default="scope">
                {{ scope.row.max_discount }}%
              </template>
            </el-table-column>
            <el-table-column label="Действия" width="120">
              <template #default="scope">
                <el-button @click="editProduct(scope.row)" type="text" size="small">
                  <el-icon><Edit /></el-icon>
                </el-button>
                <el-button @click="deleteProduct(scope.row)" type="text" size="small">
                  <el-icon><Delete /></el-icon>
                </el-button>
              </template>
            </el-table-column>
          </el-table>

          <el-pagination
            v-if="pagination.total > 0"
            @size-change="handleSizeChange"
            @current-change="handleCurrentChange"
            :current-page="pagination.page"
            :page-sizes="[10, 20, 50, 100]"
            :page-size="pagination.limit"
            layout="total, sizes, prev, pager, next, jumper"
            :total="pagination.total"
            style="margin-top: 20px; text-align: center;"
          />
        </el-card>
      </el-col>
    </el-row>

    <!-- Диалог создания/редактирования категории -->
    <el-dialog 
      :title="editingCategory ? 'Редактировать категорию' : 'Новая категория'"
      v-model="showCategoryForm"
      width="400px"
    >
      <el-form :model="categoryForm" label-width="120px">
        <el-form-item label="Название">
          <el-input v-model="categoryForm.name" placeholder="Введите название категории" />
        </el-form-item>
        <el-form-item label="Родительская категория">
          <el-select v-model="categoryForm.parent_id" placeholder="Выберите родительскую категорию" clearable style="width: 100%">
            <el-option 
              :label="'Корневая категория'" 
              :value="0"
            />
            <el-option 
              v-for="cat in flatCategories" 
              :key="cat.id" 
              :label="cat.displayName" 
              :value="cat.id"
              :disabled="editingCategory && cat.id === editingCategory.id"
            />
          </el-select>
        </el-form-item>
        <el-form-item label="Описание">
          <el-input 
            v-model="categoryForm.description" 
            type="textarea" 
            :rows="3"
            placeholder="Введите описание категории"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button @click="showCategoryForm = false">Отмена</el-button>
          <el-button type="primary" @click="saveCategory">Сохранить</el-button>
        </div>
      </template>
    </el-dialog>

    <!-- Диалог создания/редактирования товара -->
    <el-dialog 
      :title="editingProduct ? 'Редактировать товар' : 'Новый товар'"
      v-model="showProductForm"
      width="800px"
    >
      <el-form :model="productForm" label-width="150px">
        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="Название" required>
              <el-input v-model="productForm.name" placeholder="Название товара" />
            </el-form-item>
            <el-form-item label="Категория" required>
              <el-select v-model="productForm.category_id" placeholder="Выберите категорию" style="width: 100%">
                <el-option 
                  v-for="cat in categories" 
                  :key="cat.id" 
                  :label="cat.name" 
                  :value="cat.id"
                />
              </el-select>
            </el-form-item>
            <el-form-item label="Цена" required>
              <el-input-number v-model="productForm.price" :precision="2" :min="0" style="width: 100%" />
            </el-form-item>
            <el-form-item label="Штрихкод">
              <el-input v-model="productForm.barcode" placeholder="EAN код" />
            </el-form-item>
            <el-form-item label="Legacy Path">
              <el-input v-model="productForm.legacy_path" placeholder="Путь из старой системы" />
            </el-form-item>
            <el-form-item label="Единица измерения">
              <el-input v-model="productForm.unit" placeholder="шт" />
            </el-form-item>
          </el-col>
          
          <el-col :span="12">
            <el-form-item label="Описание">
              <el-input 
                v-model="productForm.description" 
                type="textarea" 
                :rows="3"
                placeholder="Описание товара"
              />
            </el-form-item>
            <el-form-item label="Макс. скидка (%)">
              <el-input-number v-model="productForm.max_discount" :min="0" :max="100" style="width: 100%" />
            </el-form-item>
            <el-form-item label="НДС (%)">
              <el-input-number v-model="productForm.tax_rate" :min="0" :max="100" style="width: 100%" />
            </el-form-item>
            
            <el-form-item label="Особенности">
              <el-checkbox v-model="productForm.is_alcohol">Алкогольный товар</el-checkbox>
              <el-checkbox v-model="productForm.is_marked">Маркированный товар</el-checkbox>
              <el-checkbox v-model="productForm.is_draught" :disabled="!productForm.is_alcohol">Разливное</el-checkbox>
              <el-checkbox v-model="productForm.is_bottled" :disabled="!productForm.is_alcohol">Бутылочное</el-checkbox>
            </el-form-item>

            <!-- ЕГАИС поля (показываются только для алкоголя) -->
            <div v-if="productForm.is_alcohol">
              <el-form-item label="Алкокод">
                <el-input v-model="productForm.alc_code" placeholder="Код алкогольной продукции" />
              </el-form-item>
              <el-form-item label="GTIN" v-if="productForm.is_marked">
                <el-input v-model="productForm.gtin" placeholder="GTIN для маркированных товаров" />
              </el-form-item>
            </div>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button @click="showProductForm = false">Отмена</el-button>
          <el-button type="primary" @click="saveProduct">Сохранить</el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script>
import api from '../api/index.js'
import { Plus, Edit, Delete, Refresh } from '@element-plus/icons-vue'

export default {
  name: 'ProductsView',
  components: {
    Plus,
    Edit,
    Delete,
    Refresh
  },
  data() {
    return {
      loading: false,
      categories: [],
      products: [],
      selectedCategory: null,
      pagination: {
        page: 1,
        limit: 20,
        total: 0
      },
      
      // Формы
      showCategoryForm: false,
      showProductForm: false,
      editingCategory: null,
      editingProduct: null,
      
      categoryForm: {
        name: '',
        description: '',
        parent_id: null
      },
      
      productForm: {
        name: '',
        description: '',
        category_id: null,
        price: 0,
        barcode: '',
        legacy_path: '',
        unit: 'шт',
        max_discount: 100,
        tax_rate: 20,
        is_alcohol: false,
        is_marked: false,
        is_draught: false,
        is_bottled: false,
        alc_code: '',
        egais_mark_code: '',
        gtin: ''
      }
    }
  },
  
  computed: {
    // Плоский список всех категорий для выбора родительской
    flatCategories() {
      const flatten = (tree, level = 0) => {
        let result = []
        for (const cat of tree) {
          result.push({
            ...cat,
            level: level,
            displayName: '  '.repeat(level) + cat.name
          })
          if (cat.children && cat.children.length > 0) {
            result = result.concat(flatten(cat.children, level + 1))
          }
        }
        return result
      }
      return flatten(this.categoriesTree)
    },
    
    // Иерархическая структура категорий для дерева
    categoriesTree() {
      const buildTree = (categories, parentId = null) => {
        return categories
          .filter(cat => (cat.parent_id === null && parentId === null) || (cat.parent_id === parentId))
          .map(cat => ({
            id: cat.id,
            name: cat.name,
            description: cat.description,
            parent_id: cat.parent_id,
            children: buildTree(categories, cat.id)
          }))
      }
      return buildTree(this.categories)
    }
  },
  
  mounted() {
    this.loadCategories()
    this.loadProducts()
  },
  
  methods: {
    async refresh() {
      this.$message.info('Обновление данных...')
      await Promise.all([
        this.loadCategories(),
        this.loadProducts()
      ])
      this.$message.success('Данные обновлены')
    },
    
    async loadCategories() {
      try {
        const response = await api.get('/categories')
        if (response.data.status === 'success') {
          this.categories = response.data.data
          console.log('Категории загружены:', this.categories)
        } else {
          this.$message.error('Ошибка загрузки категорий: ' + response.data.message)
        }
      } catch (error) {
        console.error('Ошибка загрузки категорий:', error)
        this.$message.error('Ошибка загрузки категорий: ' + (error.response?.data?.message || error.message))
      }
    },
    
    async loadProducts() {
      this.loading = true
      try {
        const params = {
          page: this.pagination.page,
          limit: this.pagination.limit
        }
        
        if (this.selectedCategory) {
          params.category_id = this.selectedCategory.id
        }
        
        const response = await api.get('/products', { params })
        if (response.data.status === 'success') {
          this.products = response.data.data
          this.pagination = response.data.pagination
          console.log('Товары загружены:', this.products)
        } else {
          this.$message.error('Ошибка загрузки товаров: ' + response.data.message)
        }
      } catch (error) {
        console.error('Ошибка загрузки товаров:', error)
        this.$message.error('Ошибка загрузки товаров: ' + (error.response?.data?.message || error.message))
      } finally {
        this.loading = false
      }
    },
    
    selectCategory(category) {
      this.selectedCategory = category
      this.pagination.page = 1
      this.loadProducts()
    },
    
    // Категории
    addCategory() {
      this.editingCategory = null
      this.categoryForm = { name: '', description: '', parent_id: null }
      this.showCategoryForm = true
    },
    
    editCategory(category) {
      this.editingCategory = category
      this.categoryForm = {
        name: category.name,
        description: category.description || '',
        parent_id: category.parent_id || 0
      }
      this.showCategoryForm = true
    },
    
    async saveCategory() {
      try {
        const formData = new FormData()
        formData.append('name', this.categoryForm.name)
        if (this.categoryForm.description) {
          formData.append('description', this.categoryForm.description)
        }
        
        // Обработка parent_id
        if (this.categoryForm.parent_id !== null && this.categoryForm.parent_id !== undefined) {
          if (this.categoryForm.parent_id === 0) {
            // Корневая категория - отправляем 0 для обновления, для создания не отправляем
            if (this.editingCategory) {
              formData.append('parent_id', '0')
            }
            // При создании не отправляем parent_id, будет создана корневая категория
          } else {
            formData.append('parent_id', this.categoryForm.parent_id.toString())
          }
        }
        
        if (this.editingCategory) {
          await api.put(`/categories/${this.editingCategory.id}`, formData)
          this.$message.success('Категория обновлена')
        } else {
          await api.post('/categories', formData)
          this.$message.success('Категория создана')
        }
        
        this.showCategoryForm = false
        this.editingCategory = null
        this.categoryForm = { name: '', description: '', parent_id: null }
        this.loadCategories()
      } catch (error) {
        this.$message.error('Ошибка сохранения категории: ' + error.message)
      }
    },
    
    async deleteCategory(category) {
      try {
        await this.$confirm(`Удалить категорию "${category.name}"?`, 'Подтверждение', {
          confirmButtonText: 'Удалить',
          cancelButtonText: 'Отмена',
          type: 'warning'
        })
        
        await api.delete(`/categories/${category.id}`)
        this.$message.success('Категория удалена')
        this.loadCategories()
        
        if (this.selectedCategory && this.selectedCategory.id === category.id) {
          this.selectedCategory = null
          this.loadProducts()
        }
      } catch (error) {
        if (error !== 'cancel') {
          this.$message.error('Ошибка удаления категории: ' + error.message)
        }
      }
    },
    
    // Товары
    addProduct() {
      this.editingProduct = null
      this.resetProductForm()
      this.showProductForm = true
    },
    
    editProduct(product) {
      this.editingProduct = product
      this.productForm = { ...product }
      this.productForm.category_id = product.category.id
      this.showProductForm = true
    },
    
    async saveProduct() {
      try {
        if (this.editingProduct) {
          await api.put(`/products/${this.editingProduct.id}`, this.productForm)
          this.$message.success('Товар обновлен')
        } else {
          await api.post('/products', this.productForm)
          this.$message.success('Товар создан')
        }
        
        this.showProductForm = false
        this.editingProduct = null
        this.resetProductForm()
        this.loadProducts()
      } catch (error) {
        this.$message.error('Ошибка сохранения товара: ' + error.message)
      }
    },
    
    async deleteProduct(product) {
      try {
        await this.$confirm(`Удалить товар "${product.name}"?`, 'Подтверждение', {
          confirmButtonText: 'Удалить',
          cancelButtonText: 'Отмена',
          type: 'warning'
        })
        
        await api.delete(`/products/${product.id}`)
        this.$message.success('Товар удален')
        this.loadProducts()
      } catch (error) {
        if (error !== 'cancel') {
          this.$message.error('Ошибка удаления товара: ' + error.message)
        }
      }
    },
    
    resetProductForm() {
      this.productForm = {
        name: '',
        description: '',
        category_id: this.selectedCategory ? this.selectedCategory.id : null,
        price: 0,
        barcode: '',
        legacy_path: '',
        unit: 'шт',
        max_discount: 100,
        tax_rate: 20,
        is_alcohol: false,
        is_marked: false,
        is_draught: false,
        is_bottled: false,
        alc_code: '',
        egais_mark_code: '',
        gtin: ''
      }
    },
    
    // Пагинация
    handleSizeChange(val) {
      this.pagination.limit = val
      this.pagination.page = 1
      this.loadProducts()
    },
    
    handleCurrentChange(val) {
      this.pagination.page = val
      this.loadProducts()
    }
  },
  
  watch: {
    showProductForm(val) {
      if (val && !this.editingProduct) {
        this.resetProductForm()
      }
    },
    
    showCategoryForm(val) {
      if (!val) {
        this.editingCategory = null
        this.categoryForm = { name: '', description: '' }
      }
    }
  }
}
</script>

<style scoped>
.custom-tree-node {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: 14px;
  padding-right: 8px;
}

.el-tree-node__content:hover .custom-tree-node span:last-child {
  display: inline-block;
}

.custom-tree-node span:last-child {
  display: none;
}

.clearfix:before,
.clearfix:after {
  display: table;
  content: "";
}
.clearfix:after {
  clear: both
}
</style>

// client/src/components/ProductsView.svelte
<script>
import { onMount } from "svelte";
import api from "../lib/api.js";

let loading = false;
let categories = [];
let products = [];
let selectedCategory = null;
let pagination = {
	page: 1,
	limit: 20,
	total: 0,
};

let showCategoryForm = false;
let showProductForm = false;
let editingCategory = null;
let editingProduct = null;

let categoryForm = {
	name: "",
	description: "",
	parent_id: null,
};

let productForm = {
	name: "",
	description: "",
	category_id: null,
	price: 0,
	barcode: "",
	legacy_path: "",
	unit: "шт",
	max_discount: 100,
	tax_rate: 20,
	is_alcohol: false,
	is_marked: false,
	is_draught: false,
	is_bottled: false,
	alc_code: "",
	egais_mark_code: "",
	gtin: "",
};

$: categoriesTree = buildTree(categories);
$: flatCategories = flattenCategories(categoriesTree);

function buildTree(cats, parentId = null) {
	return cats
		.filter(
			(cat) =>
				(cat.parent_id === null && parentId === null) ||
				cat.parent_id === parentId
		)
		.map((cat) => ({
			id: cat.id,
			name: cat.name,
			description: cat.description,
			parent_id: cat.parent_id,
			children: buildTree(cats, cat.id),
		}));
}

function flattenCategories(tree, level = 0) {
	let result = [];
	for (const cat of tree) {
		result.push({
			...cat,
			level: level,
			displayName: "  ".repeat(level) + cat.name,
		});
		if (cat.children && cat.children.length > 0) {
			result = result.concat(flattenCategories(cat.children, level + 1));
		}
	}
	return result;
}

onMount(async () => {
	await loadCategories();
	await loadProducts();
});

async function refresh() {
	await Promise.all([loadCategories(), loadProducts()]);
}

async function loadCategories() {
	try {
		const response = await api.get("/categories");
		if (response.data.status === "success") {
			categories = response.data.data;
		}
	} catch (error) {
		console.error("Ошибка загрузки категорий:", error);
	}
}

async function loadProducts() {
	loading = true;
	try {
		const params = {
			page: pagination.page,
			limit: pagination.limit,
		};

		if (selectedCategory) {
			params.category_id = selectedCategory.id;
		}

		const response = await api.get("/products", { params });
		if (response.data.status === "success") {
			products = response.data.data;
			pagination = response.data.pagination;
		}
	} catch (error) {
		console.error("Ошибка загрузки товаров:", error);
	} finally {
		loading = false;
	}
}

function selectCategory(category) {
	selectedCategory = category;
	pagination.page = 1;
	loadProducts();
}

function addCategory() {
	editingCategory = null;
	categoryForm = { name: "", description: "", parent_id: null };
	showCategoryForm = true;
}

function editCategory(category) {
	editingCategory = category;
	categoryForm = {
		name: category.name,
		description: category.description || "",
		parent_id: category.parent_id || 0,
	};
	showCategoryForm = true;
}

async function saveCategory() {
	try {
		const formData = new FormData();
		formData.append("name", categoryForm.name);
		if (categoryForm.description) {
			formData.append("description", categoryForm.description);
		}

		if (
			categoryForm.parent_id !== null &&
			categoryForm.parent_id !== undefined &&
			categoryForm.parent_id !== 0
		) {
			formData.append("parent_id", categoryForm.parent_id.toString());
		}

		if (editingCategory) {
			await api.put(`/categories/${editingCategory.id}`, formData);
		} else {
			await api.post("/categories", formData);
		}

		showCategoryForm = false;
		editingCategory = null;
		categoryForm = { name: "", description: "", parent_id: null };
		await loadCategories();
	} catch (error) {
		alert("Ошибка сохранения категории: " + error.message);
	}
}

async function deleteCategory(category) {
	if (!confirm(`Удалить категорию "${category.name}"?`)) return;

	try {
		await api.delete(`/categories/${category.id}`);
		await loadCategories();

		if (selectedCategory && selectedCategory.id === category.id) {
			selectedCategory = null;
			await loadProducts();
		}
	} catch (error) {
		alert("Ошибка удаления категории: " + error.message);
	}
}

function addProduct() {
	editingProduct = null;
	resetProductForm();
	showProductForm = true;
}

function editProduct(product) {
	editingProduct = product;
	productForm = { ...product };
	productForm.category_id = product.category.id;
	showProductForm = true;
}

async function saveProduct() {
	try {
		if (editingProduct) {
			await api.put(`/products/${editingProduct.id}`, productForm);
		} else {
			await api.post("/products", productForm);
		}

		showProductForm = false;
		editingProduct = null;
		resetProductForm();
		await loadProducts();
	} catch (error) {
		alert("Ошибка сохранения товара: " + error.message);
	}
}

async function deleteProduct(product) {
	if (!confirm(`Удалить товар "${product.name}"?`)) return;

	try {
		await api.delete(`/products/${product.id}`);
		await loadProducts();
	} catch (error) {
		alert("Ошибка удаления товара: " + error.message);
	}
}

function resetProductForm() {
	productForm = {
		name: "",
		description: "",
		category_id: selectedCategory ? selectedCategory.id : null,
		price: 0,
		barcode: "",
		legacy_path: "",
		unit: "шт",
		max_discount: 100,
		tax_rate: 20,
		is_alcohol: false,
		is_marked: false,
		is_draught: false,
		is_bottled: false,
		alc_code: "",
		egais_mark_code: "",
		gtin: "",
	};
}

function handleSizeChange(val) {
	pagination.limit = val;
	pagination.page = 1;
	loadProducts();
}

function handleCurrentChange(val) {
	pagination.page = val;
	loadProducts();
}
</script>

<div class="grid grid-cols-6 gap-4">
  <!-- Категории -->
  <div class="col-span-2">
    <div class="card">
      <div class="flex justify-between items-center mb-4">
        <h3 class="text-lg font-semibold">Категории</h3>
        <button class="btn btn-primary text-sm" on:click={addCategory}>
          + Добавить
        </button>
      </div>
      
      <div class="space-y-1 max-h-96 overflow-y-auto">
        {#each categoriesTree as category}
          <div class="p-2 hover:bg-gray-100 rounded cursor-pointer {selectedCategory?.id === category.id ? 'bg-primary-50' : ''}"
               on:click={() => selectCategory(category)}>
            <div class="flex justify-between items-center">
              <span>{category.name}</span>
              <div class="flex gap-1">
                <button class="text-primary-500 hover:text-primary-700" on:click|stopPropagation={() => editCategory(category)}>
                  ✏️
                </button>
                <button class="text-danger-500 hover:text-danger-700" on:click|stopPropagation={() => deleteCategory(category)}>
                  🗑️
                </button>
              </div>
            </div>
          </div>
        {/each}
      </div>
    </div>
  </div>

  <!-- Товары -->
  <div class="col-span-4">
    <div class="card">
      <div class="flex justify-between items-center mb-4">
        <h3 class="text-lg font-semibold">Товары</h3>
        <div class="flex gap-2">
          <button class="btn btn-secondary text-sm" on:click={refresh}>Обновить</button>
          <button class="btn btn-primary text-sm" on:click={addProduct}>+ Добавить товар</button>
        </div>
      </div>

      {#if loading}
        <div class="text-center py-8">Загрузка...</div>
      {:else}
        <div class="overflow-x-auto">
          <table class="w-full border-collapse">
            <thead>
              <tr class="bg-gray-100">
                <th class="border border-gray-300 px-4 py-2 text-left">Название</th>
                <th class="border border-gray-300 px-4 py-2 text-left">Цена</th>
                <th class="border border-gray-300 px-4 py-2 text-left">Штрихкод</th>
                <th class="border border-gray-300 px-4 py-2 text-left">Ед. изм.</th>
                <th class="border border-gray-300 px-4 py-2 text-left">Особенности</th>
                <th class="border border-gray-300 px-4 py-2 text-left">Макс. скидка</th>
                <th class="border border-gray-300 px-4 py-2 text-left">Действия</th>
              </tr>
            </thead>
            <tbody>
              {#each products as product}
                <tr class="hover:bg-gray-50">
                  <td class="border border-gray-300 px-4 py-2">{product.name}</td>
                  <td class="border border-gray-300 px-4 py-2">{product.price} Р</td>
                  <td class="border border-gray-300 px-4 py-2">{product.barcode || '-'}</td>
                  <td class="border border-gray-300 px-4 py-2">{product.unit}</td>
                  <td class="border border-gray-300 px-4 py-2">
                    <div class="flex gap-1">
                      {#if product.is_alcohol}
                        <span class="px-2 py-1 bg-warning-100 text-warning-700 rounded text-xs">Алко</span>
                      {/if}
                      {#if product.is_marked}
                        <span class="px-2 py-1 bg-danger-100 text-danger-700 rounded text-xs">Марк.</span>
                      {/if}
                      {#if product.is_draught}
                        <span class="px-2 py-1 bg-gray-100 text-gray-700 rounded text-xs">Разл.</span>
                      {/if}
                    </div>
                  </td>
                  <td class="border border-gray-300 px-4 py-2">{product.max_discount}%</td>
                  <td class="border border-gray-300 px-4 py-2">
                    <div class="flex gap-2">
                      <button class="text-primary-500 hover:text-primary-700" on:click={() => editProduct(product)}>✏️</button>
                      <button class="text-danger-500 hover:text-danger-700" on:click={() => deleteProduct(product)}>🗑️</button>
                    </div>
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>

        {#if pagination.total > 0}
          <div class="flex justify-between items-center mt-4">
            <div class="text-sm text-gray-600">
              Показано {((pagination.page - 1) * pagination.limit) + 1} - {Math.min(pagination.page * pagination.limit, pagination.total)} из {pagination.total}
            </div>
            <div class="flex gap-2">
              <button
                class="btn btn-secondary text-sm"
                disabled={pagination.page === 1}
                on:click={() => handleCurrentChange(pagination.page - 1)}
              >
                Назад
              </button>
              <button
                class="btn btn-secondary text-sm"
                disabled={pagination.page * pagination.limit >= pagination.total}
                on:click={() => handleCurrentChange(pagination.page + 1)}
              >
                Вперед
              </button>
            </div>
          </div>
        {/if}
      {/if}
    </div>
  </div>
</div>

<!-- Диалог категории -->
{#if showCategoryForm}
  <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
    <div class="card w-full max-w-md">
      <h3 class="text-lg font-semibold mb-4">{editingCategory ? 'Редактировать категорию' : 'Новая категория'}</h3>
      
      <div class="space-y-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Название</label>
          <input type="text" class="input" bind:value={categoryForm.name} placeholder="Введите название категории" />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Родительская категория</label>
          <select class="input" bind:value={categoryForm.parent_id}>
            <option value={0}>Корневая категория</option>
            {#each flatCategories as cat}
              <option value={cat.id} disabled={editingCategory && cat.id === editingCategory.id}>
                {cat.displayName}
              </option>
            {/each}
          </select>
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Описание</label>
          <textarea class="input" rows="3" bind:value={categoryForm.description} placeholder="Введите описание категории"></textarea>
        </div>
      </div>
      
      <div class="flex gap-3 mt-6">
        <button class="btn btn-secondary flex-1" on:click={() => showCategoryForm = false}>Отмена</button>
        <button class="btn btn-primary flex-1" on:click={saveCategory}>Сохранить</button>
      </div>
    </div>
  </div>
{/if}

<!-- Диалог товара -->
{#if showProductForm}
  <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 overflow-y-auto p-4">
    <div class="card w-full max-w-4xl my-8">
      <h3 class="text-lg font-semibold mb-4">{editingProduct ? 'Редактировать товар' : 'Новый товар'}</h3>
      
      <div class="grid grid-cols-2 gap-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Название *</label>
          <input type="text" class="input" bind:value={productForm.name} placeholder="Название товара" />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Категория *</label>
          <select class="input" bind:value={productForm.category_id}>
            <option value={null}>Выберите категорию</option>
            {#each flatCategories as cat}
              <option value={cat.id}>{cat.displayName}</option>
            {/each}
          </select>
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Цена *</label>
          <input type="number" class="input" bind:value={productForm.price} min="0" step="0.01" />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Штрихкод</label>
          <input type="text" class="input" bind:value={productForm.barcode} placeholder="EAN код" />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Legacy Path</label>
          <input type="text" class="input" bind:value={productForm.legacy_path} placeholder="Путь из старой системы" />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Единица измерения</label>
          <input type="text" class="input" bind:value={productForm.unit} placeholder="шт" />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Макс. скидка (%)</label>
          <input type="number" class="input" bind:value={productForm.max_discount} min="0" max="100" />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">НДС (%)</label>
          <input type="number" class="input" bind:value={productForm.tax_rate} min="0" max="100" />
        </div>
        <div class="col-span-2">
          <label class="block text-sm font-medium text-gray-700 mb-1">Описание</label>
          <textarea class="input" rows="3" bind:value={productForm.description} placeholder="Описание товара"></textarea>
        </div>
        <div class="col-span-2">
          <label class="block text-sm font-medium text-gray-700 mb-2">Особенности</label>
          <div class="space-y-2">
            <label class="flex items-center gap-2">
              <input type="checkbox" bind:checked={productForm.is_alcohol} />
              <span>Алкогольный товар</span>
            </label>
            <label class="flex items-center gap-2">
              <input type="checkbox" bind:checked={productForm.is_marked} />
              <span>Маркированный товар</span>
            </label>
            <label class="flex items-center gap-2">
              <input type="checkbox" bind:checked={productForm.is_draught} disabled={!productForm.is_alcohol} />
              <span>Разливное</span>
            </label>
            <label class="flex items-center gap-2">
              <input type="checkbox" bind:checked={productForm.is_bottled} disabled={!productForm.is_alcohol} />
              <span>Бутылочное</span>
            </label>
          </div>
        </div>
        
        {#if productForm.is_alcohol}
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Алкокод</label>
            <input type="text" class="input" bind:value={productForm.alc_code} placeholder="Код алкогольной продукции" />
          </div>
          {#if productForm.is_marked}
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">GTIN</label>
              <input type="text" class="input" bind:value={productForm.gtin} placeholder="GTIN для маркированных товаров" />
            </div>
          {/if}
        {/if}
      </div>
      
      <div class="flex gap-3 mt-6">
        <button class="btn btn-secondary flex-1" on:click={() => showProductForm = false}>Отмена</button>
        <button class="btn btn-primary flex-1" on:click={saveProduct}>Сохранить</button>
      </div>
    </div>
  </div>
{/if}
