// client/src/components/UsersView.vue
<template>
  <div>
    <el-card>
      <template #header>
        <div class="clearfix">
          <span>Управление пользователями</span>
          <el-button 
            style="float: right; padding: 3px 0" 
            type="primary" 
            @click="showAddDialog"
          >
            <el-icon><Plus /></el-icon> Добавить пользователя
          </el-button>
        </div>
      </template>

      <el-table :data="users" v-loading="loading" style="width: 100%">
        <el-table-column prop="username" label="Имя пользователя" width="200" />
        <el-table-column label="Статус" width="100">
          <template #default="scope">
            <el-tag v-if="scope.row.is_active" type="success">Активен</el-tag>
            <el-tag v-else type="info">Деактивирован</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="created_at" label="Дата создания" width="180">
          <template #default="scope">
            {{ formatDate(scope.row.created_at) }}
          </template>
        </el-table-column>
        <el-table-column label="Действия" width="150">
          <template #default="scope">
            <el-button @click="editUser(scope.row)" type="text" size="small">
              <el-icon><Edit /></el-icon>
            </el-button>
            <el-button 
              @click="deleteUser(scope.row)" 
              type="text" 
              size="small"
              :disabled="!scope.row.is_active"
            >
              <el-icon><Delete /></el-icon>
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- Диалог создания/редактирования пользователя -->
    <el-dialog
      :title="editMode ? 'Редактировать пользователя' : 'Добавить пользователя'"
      v-model="dialogVisible"
      width="500px"
    >
      <el-form :model="userForm" :rules="rules" ref="userFormRef" label-width="150px">
        <el-form-item label="Имя пользователя" prop="username">
          <el-input v-model="userForm.username" />
        </el-form-item>
        
        <el-form-item 
          :label="editMode ? 'Новый пароль' : 'Пароль'" 
          prop="password"
          :required="!editMode"
        >
          <el-input 
            v-model="userForm.password" 
            type="password" 
            show-password
            :placeholder="editMode ? 'Оставьте пустым, чтобы не менять' : ''"
          />
        </el-form-item>
        
        <el-form-item label="Статус">
          <el-switch 
            v-model="userForm.is_active" 
            active-text="Активен"
            inactive-text="Деактивирован"
          />
        </el-form-item>
      </el-form>

      <template #footer>
        <span class="dialog-footer">
          <el-button @click="dialogVisible = false">Отмена</el-button>
          <el-button type="primary" @click="saveUser">Сохранить</el-button>
        </span>
      </template>
    </el-dialog>
  </div>
</template>

<script>
import { usersApi } from '../api'
import { Plus, Edit, Delete } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'

export default {
  name: 'UsersView',
  components: {
    Plus,
    Edit,
    Delete
  },
  data() {
    // Валидация пароля при создании
    const validatePassword = (rule, value, callback) => {
      if (!this.editMode && !value) {
        callback(new Error('Пароль обязателен при создании'))
      } else {
        callback()
      }
    }

    return {
      users: [],
      loading: false,
      dialogVisible: false,
      editMode: false,
      userForm: {
        username: '',
        password: '',
        is_active: true
      },
      rules: {
        username: [
          { required: true, message: 'Введите имя пользователя', trigger: 'blur' }
        ],
        password: [
          { validator: validatePassword, trigger: 'blur' }
        ]
      }
    }
  },
  mounted() {
    console.log('UsersView mounted')
    this.loadUsers()
  },
  methods: {
    async loadUsers() {
      this.loading = true
      try {
        console.log('Загрузка пользователей...')
        const response = await usersApi.getUsers()
        console.log('Ответ API:', response)
        this.users = response.data.data
        console.log('Пользователи загружены:', this.users)
      } catch (error) {
        console.error('Ошибка загрузки пользователей:', error)
        ElMessage.error('Ошибка загрузки пользователей: ' + (error.response?.data?.message || error.message))
      } finally {
        this.loading = false
      }
    },
    
    showAddDialog() {
      this.editMode = false
      this.userForm = {
        username: '',
        password: '',
        is_active: true
      }
      this.dialogVisible = true
    },
    
    editUser(user) {
      this.editMode = true
      this.userForm = {
        id: user.id,
        username: user.username,
        password: '',
        is_active: user.is_active
      }
      this.dialogVisible = true
    },
    
    async saveUser() {
      try {
        await this.$refs.userFormRef.validate()
        
        const userData = {
          username: this.userForm.username,
          is_active: this.userForm.is_active
        }
        
        // Добавляем пароль только если он указан
        if (this.userForm.password) {
          userData.password = this.userForm.password
        }
        
        if (this.editMode) {
          await usersApi.updateUser(this.userForm.id, userData)
          ElMessage.success('Пользователь обновлен')
        } else {
          await usersApi.createUser(userData)
          ElMessage.success('Пользователь создан')
        }
        
        this.dialogVisible = false
        await this.loadUsers()
      } catch (error) {
        if (error.errors) {
          // Ошибки валидации формы
          return
        }
        ElMessage.error('Ошибка сохранения: ' + error.message)
      }
    },
    
    async deleteUser(user) {
      try {
        await ElMessageBox.confirm(
          `Вы уверены, что хотите деактивировать пользователя "${user.username}"?`,
          'Подтверждение',
          {
            confirmButtonText: 'Да',
            cancelButtonText: 'Отмена',
            type: 'warning'
          }
        )
        
        await usersApi.deleteUser(user.id)
        ElMessage.success('Пользователь деактивирован')
        await this.loadUsers()
      } catch (error) {
        if (error !== 'cancel') {
          ElMessage.error('Ошибка удаления: ' + error.message)
        }
      }
    },
    
    formatDate(dateString) {
      if (!dateString) return '-'
      const date = new Date(dateString)
      return date.toLocaleString('ru-RU', {
        year: 'numeric',
        month: '2-digit',
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit'
      })
    }
  }
}
</script>

<style scoped>
.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
}
</style>

// client/src/components/UsersView.svelte
<script>
import { onMount } from "svelte";
import { usersApi } from "../lib/api.js";

let users = [];
let loading = false;
let dialogVisible = false;
let editMode = false;
let userForm = {
	username: "",
	password: "",
	is_active: true,
};

onMount(() => {
	loadUsers();
});

async function loadUsers() {
	loading = true;
	try {
		const response = await usersApi.getUsers();
		users = response.data.data;
	} catch (error) {
		alert(
			"Ошибка загрузки пользователей: " +
				(error.response?.data?.message || error.message)
		);
	} finally {
		loading = false;
	}
}

function showAddDialog() {
	editMode = false;
	userForm = { username: "", password: "", is_active: true };
	dialogVisible = true;
}

function editUser(user) {
	editMode = true;
	userForm = {
		id: user.id,
		username: user.username,
		password: "",
		is_active: user.is_active,
	};
	dialogVisible = true;
}

async function saveUser() {
	if (!userForm.username) {
		alert("Введите имя пользователя");
		return;
	}

	if (!editMode && !userForm.password) {
		alert("Введите пароль");
		return;
	}

	try {
		const userData = {
			username: userForm.username,
			is_active: userForm.is_active,
		};

		if (userForm.password) {
			userData.password = userForm.password;
		}

		if (editMode) {
			await usersApi.updateUser(userForm.id, userData);
			alert("Пользователь обновлен");
		} else {
			await usersApi.createUser(userData);
			alert("Пользователь создан");
		}

		dialogVisible = false;
		await loadUsers();
	} catch (error) {
		alert("Ошибка сохранения: " + error.message);
	}
}

async function deleteUser(user) {
	if (
		!confirm(
			`Вы уверены, что хотите деактивировать пользователя "${user.username}"?`
		)
	) {
		return;
	}

	try {
		await usersApi.deleteUser(user.id);
		alert("Пользователь деактивирован");
		await loadUsers();
	} catch (error) {
		alert("Ошибка удаления: " + error.message);
	}
}

function formatDate(dateString) {
	if (!dateString) return "-";
	const date = new Date(dateString);
	return date.toLocaleString("ru-RU", {
		year: "numeric",
		month: "2-digit",
		day: "2-digit",
		hour: "2-digit",
		minute: "2-digit",
	});
}
</script>

<div class="card">
    <div class="flex justify-between items-center mb-4">
        <h2 class="text-xl font-semibold">Управление пользователями</h2>
        <button class="btn btn-primary" on:click={showAddDialog}>
            + Добавить пользователя
        </button>
    </div>

    {#if loading}
        <div class="text-center py-8">Загрузка...</div>
    {:else}
        <div class="overflow-x-auto">
            <table class="w-full border-collapse">
                <thead>
                    <tr class="bg-gray-100">
                        <th class="border border-gray-300 px-4 py-2 text-left"
                            >Имя пользователя</th
                        >
                        <th class="border border-gray-300 px-4 py-2 text-left"
                            >Статус</th
                        >
                        <th class="border border-gray-300 px-4 py-2 text-left"
                            >Дата создания</th
                        >
                        <th class="border border-gray-300 px-4 py-2 text-left"
                            >Действия</th
                        >
                    </tr>
                </thead>
                <tbody>
                    {#each users as user}
                        <tr class="hover:bg-gray-50">
                            <td class="border border-gray-300 px-4 py-2"
                                >{user.username}</td
                            >
                            <td class="border border-gray-300 px-4 py-2">
                                {#if user.is_active}
                                    <span
                                        class="px-2 py-1 bg-success-100 text-success-700 rounded text-sm"
                                        >Активен</span
                                    >
                                {:else}
                                    <span
                                        class="px-2 py-1 bg-gray-100 text-gray-700 rounded text-sm"
                                        >Деактивирован</span
                                    >
                                {/if}
                            </td>
                            <td class="border border-gray-300 px-4 py-2"
                                >{formatDate(user.created_at)}</td
                            >
                            <td class="border border-gray-300 px-4 py-2">
                                <div class="flex gap-2">
                                    <button
                                        class="text-primary-500 hover:text-primary-700"
                                        on:click={() => editUser(user)}
                                        >✏️</button
                                    >
                                    <button
                                        class="text-danger-500 hover:text-danger-700 {!user.is_active
                                            ? 'opacity-50 cursor-not-allowed'
                                            : ''}"
                                        on:click={() => deleteUser(user)}
                                        disabled={!user.is_active}
                                    >
                                        🗑️
                                    </button>
                                </div>
                            </td>
                        </tr>
                    {/each}
                </tbody>
            </table>
        </div>
    {/if}
</div>

<!-- Диалог создания/редактирования пользователя -->
{#if dialogVisible}
    <div
        class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
    >
        <div class="card w-full max-w-md">
            <h3 class="text-lg font-semibold mb-4">
                {editMode
                    ? "Редактировать пользователя"
                    : "Добавить пользователя"}
            </h3>

            <div class="space-y-4">
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1"
                        >Имя пользователя *</label
                    >
                    <input
                        type="text"
                        class="input"
                        bind:value={userForm.username}
                    />
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">
                        {editMode ? "Новый пароль" : "Пароль"}
                        {editMode ? "" : "*"}
                    </label>
                    <input
                        type="password"
                        class="input"
                        bind:value={userForm.password}
                        placeholder={editMode
                            ? "Оставьте пустым, чтобы не менять"
                            : ""}
                    />
                </div>

                <div>
                    <label class="flex items-center gap-2">
                        <input
                            type="checkbox"
                            bind:checked={userForm.is_active}
                        />
                        <span>Активен</span>
                    </label>
                </div>
            </div>

            <div class="flex gap-3 mt-6">
                <button
                    class="btn btn-secondary flex-1"
                    on:click={() => (dialogVisible = false)}>Отмена</button
                >
                <button class="btn btn-primary flex-1" on:click={saveUser}
                    >Сохранить</button
                >
            </div>
        </div>
    </div>
{/if}
